// Code generated by mockery v2.33.0. DO NOT EDIT.

package agent

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockCleanupFiles is an autogenerated mock type for the CleanupFiles type
type MockCleanupFiles struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx
func (_m *MockCleanupFiles) Execute(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockCleanupFiles creates a new instance of MockCleanupFiles. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCleanupFiles(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCleanupFiles {
	mock := &MockCleanupFiles{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
