evans:
	evans --host localhost --port $(EVANS_PORT) -r repl
psql:
	PGPASSWORD=$(DB_PASSWORD) psql -h $(DB_ADDR) -U $(DB_USER) -d $(DB_NAME)

generate:
	go generate ./...

rebuild: remove build
remove:
	docker image rm -f ftgogo-$(SERVICE) $(REPO_NAME)/$(SERVICE):latest

build:
	docker build -t ftgogo-$(SERVICE) -t $(REPO_NAME)/$(SERVICE):latest \
		--build-arg SERVICE=$(SERVICE) .
