// Code generated by mockery v2.33.0. DO NOT EDIT.

package application

import (
	context "context"

	domain "github.com/rezaAmiri123/mallbots/customers/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockApp is an autogenerated mock type for the App type
type MockApp struct {
	mock.Mock
}

// GetCustomer provides a mock function with given fields: ctx, get
func (_m *MockApp) GetCustomer(ctx context.Context, get GetCustomer) (*domain.Customer, error) {
	ret := _m.Called(ctx, get)

	var r0 *domain.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, GetCustomer) (*domain.Customer, error)); ok {
		return rf(ctx, get)
	}
	if rf, ok := ret.Get(0).(func(context.Context, GetCustomer) *domain.Customer); ok {
		r0 = rf(ctx, get)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, GetCustomer) error); ok {
		r1 = rf(ctx, get)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterCustomer provides a mock function with given fields: ctx, register
func (_m *MockApp) RegisterCustomer(ctx context.Context, register RegisterCustomer) error {
	ret := _m.Called(ctx, register)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, RegisterCustomer) error); ok {
		r0 = rf(ctx, register)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockApp creates a new instance of MockApp. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockApp(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockApp {
	mock := &MockApp{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
