// Code generated by mockery v2.33.0. DO NOT EDIT.

package domain

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockCatalogRepository is an autogenerated mock type for the CatalogRepository type
type MockCatalogRepository struct {
	mock.Mock
}

// AddProduct provides a mock function with given fields: ctx, productID, storeID, name, description, sku, price
func (_m *MockCatalogRepository) AddProduct(ctx context.Context, productID string, storeID string, name string, description string, sku string, price float64) error {
	ret := _m.Called(ctx, productID, storeID, name, description, sku, price)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, float64) error); ok {
		r0 = rf(ctx, productID, storeID, name, description, sku, price)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Find provides a mock function with given fields: ctx, productID
func (_m *MockCatalogRepository) Find(ctx context.Context, productID string) (*CatalogProduct, error) {
	ret := _m.Called(ctx, productID)

	var r0 *CatalogProduct
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*CatalogProduct, error)); ok {
		return rf(ctx, productID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *CatalogProduct); ok {
		r0 = rf(ctx, productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*CatalogProduct)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockCatalogRepository creates a new instance of MockCatalogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCatalogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCatalogRepository {
	mock := &MockCatalogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
