// Code generated by mockery v2.33.0. DO NOT EDIT.

package domain

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockMallRepository is an autogenerated mock type for the MallRepository type
type MockMallRepository struct {
	mock.Mock
}

// AddStore provides a mock function with given fields: ctx, storeID, name, location
func (_m *MockMallRepository) AddStore(ctx context.Context, storeID string, name string, location string) error {
	ret := _m.Called(ctx, storeID, name, location)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, storeID, name, location)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Find provides a mock function with given fields: ctx, storeID
func (_m *MockMallRepository) Find(ctx context.Context, storeID string) (*MallStore, error) {
	ret := _m.Called(ctx, storeID)

	var r0 *MallStore
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*MallStore, error)); ok {
		return rf(ctx, storeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *MallStore); ok {
		r0 = rf(ctx, storeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*MallStore)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, storeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockMallRepository creates a new instance of MockMallRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMallRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMallRepository {
	mock := &MockMallRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
