// Code generated by mockery v2.33.0. DO NOT EDIT.

package application

import (
	context "context"

	domain "github.com/rezaAmiri123/mallbots/stores/internal/domain"
	mock "github.com/stretchr/testify/mock"

	queries "github.com/rezaAmiri123/mallbots/stores/internal/application/queries"
)

// MockQueries is an autogenerated mock type for the Queries type
type MockQueries struct {
	mock.Mock
}

// GetStore provides a mock function with given fields: ctx, query
func (_m *MockQueries) GetStore(ctx context.Context, query queries.GetStore) (*domain.MallStore, error) {
	ret := _m.Called(ctx, query)

	var r0 *domain.MallStore
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetStore) (*domain.MallStore, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetStore) *domain.MallStore); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.MallStore)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, queries.GetStore) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockQueries creates a new instance of MockQueries. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueries(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueries {
	mock := &MockQueries{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
