// Code generated by mockery v2.33.0. DO NOT EDIT.

package application

import (
	context "context"

	commands "github.com/rezaAmiri123/mallbots/stores/internal/application/commands"

	domain "github.com/rezaAmiri123/mallbots/stores/internal/domain"

	mock "github.com/stretchr/testify/mock"

	queries "github.com/rezaAmiri123/mallbots/stores/internal/application/queries"
)

// MockApp is an autogenerated mock type for the App type
type MockApp struct {
	mock.Mock
}

// AddProduct provides a mock function with given fields: ctx, cmd
func (_m *MockApp) AddProduct(ctx context.Context, cmd commands.AddProduct) error {
	ret := _m.Called(ctx, cmd)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.AddProduct) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateStore provides a mock function with given fields: ctx, cmd
func (_m *MockApp) CreateStore(ctx context.Context, cmd commands.CreateStore) error {
	ret := _m.Called(ctx, cmd)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.CreateStore) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetStore provides a mock function with given fields: ctx, query
func (_m *MockApp) GetStore(ctx context.Context, query queries.GetStore) (*domain.MallStore, error) {
	ret := _m.Called(ctx, query)

	var r0 *domain.MallStore
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetStore) (*domain.MallStore, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetStore) *domain.MallStore); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.MallStore)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, queries.GetStore) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IncreaseProductPrice provides a mock function with given fields: ctx, cmd
func (_m *MockApp) IncreaseProductPrice(ctx context.Context, cmd commands.IncreaseProductPrice) error {
	ret := _m.Called(ctx, cmd)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.IncreaseProductPrice) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockApp creates a new instance of MockApp. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockApp(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockApp {
	mock := &MockApp{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
