// Code generated by mockery v2.33.0. DO NOT EDIT.

package application

import (
	context "context"

	domain "github.com/rezaAmiri123/mallbots/baskets/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockApp is an autogenerated mock type for the App type
type MockApp struct {
	mock.Mock
}

// AddItem provides a mock function with given fields: ctx, add
func (_m *MockApp) AddItem(ctx context.Context, add AddItem) error {
	ret := _m.Called(ctx, add)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, AddItem) error); ok {
		r0 = rf(ctx, add)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CheckoutBasket provides a mock function with given fields: ctx, checkout
func (_m *MockApp) CheckoutBasket(ctx context.Context, checkout CheckoutBasket) error {
	ret := _m.Called(ctx, checkout)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, CheckoutBasket) error); ok {
		r0 = rf(ctx, checkout)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBasket provides a mock function with given fields: ctx, getbasket
func (_m *MockApp) GetBasket(ctx context.Context, getbasket GetBasket) (*domain.Basket, error) {
	ret := _m.Called(ctx, getbasket)

	var r0 *domain.Basket
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, GetBasket) (*domain.Basket, error)); ok {
		return rf(ctx, getbasket)
	}
	if rf, ok := ret.Get(0).(func(context.Context, GetBasket) *domain.Basket); ok {
		r0 = rf(ctx, getbasket)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Basket)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, GetBasket) error); ok {
		r1 = rf(ctx, getbasket)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StartBasket provides a mock function with given fields: ctx, start
func (_m *MockApp) StartBasket(ctx context.Context, start StartBasket) error {
	ret := _m.Called(ctx, start)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, StartBasket) error); ok {
		r0 = rf(ctx, start)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockApp creates a new instance of MockApp. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockApp(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockApp {
	mock := &MockApp{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
